begin
  a
rescue Exception => ex
  b
end
